### ISSUE TITLE
Unrecognized gcc arguments

### ISSUE THREAD

**Issue by command-tab** [Mr-Pnut/portable-n64-toolchain#1]
After installing Docker, the `docker build` worked great! When trying to build nu0 using this setup, though, I'm encountering a few gcc errors:

```
$ docker run -w /mnt/src -v /REDACTED/nu0:/mnt/src -it n64 make
gcc -DNU_DEBUG -DF3DEX_GBI_2 -I. -I/usr/local/n64kit/nusys/include -I/n64sdk/ultra/usr/include/PR -G 0 -c -I/n64sdk/ultra/usr/include -D_MIPS_SZLONG=34 -D_MIPS_SZINT=32 -D_LANGUAGE_C -D_ULTRA64 -D__EXTENSIONS__ -mabi=32 -march=vr4300 -mtune=vr4300 -g main.c
gcc: error: 0: No such file or directory
gcc: error: unrecognized argument in option '-mabi=32'
gcc: note: valid arguments to '-mabi=' are: ms sysv
gcc: error: unrecognized command line option '-G'
make: *** [/n64sdk/ultra/usr/include/make/commonrules:6: main.o] Error 1
```

It appears the `0: No such file or directory` is coming from the line `LCOPTS = -G 0` in the nu0 Makefile, but I'm not sure why gcc is parsing those args incorrectly.

Secondly, the `-mabi=32` reference appears to be specified here:
https://github.com/Mr-Pnut/portable-n64-toolchain/blob/4d175de74fb5694b415ee7ba106b53777c04bf23/overlays/n64sdk/ultra/usr/include/make/PRdefs#L9
But I'm not sure why `32` is not among the valid options, since this argument was specifically included as a filesystem overlay.

Thoughts?

Thanks for getting this stack all bundled up ❤️

**Comment by Mr-Pnut** [comment]
Hey commandtab, thanks for posting!

That usually means that it's using the non MIPS GCC instead of mips64-elf-gcc.

Are you referencing GCC anywhere in your Makefile or are you just using the .o rule in commonrules?

(edit)

After I looked closer, I see that it is getting invoked from commonrules.  $(CC) should be pointing to mips64-elf-gcc.

**Comment by command-tab** [comment]
I was indeed referencing `gcc`! D'oh!

I commented out `CC = gcc` and was then able to depend on `CC` being provided by the PRdefs overlay, and that seemed to invoke mips64-elf-gcc as needed.

I immediately then ran into another issue that the original Makefile referenced the wrong n64kit path. I had to update that line of the Makefile to `N64KITDIR = /n64sdk/nintendo/n64kit`, which is where it's copied by the Dockerfile.

Now I'm getting this when building:

```
ld -o codesegment.o -r main.o stage00.o graphic.o gfxinit.o  /n64sdk/nintendo/n64kit/nusys/lib/nusys.o  -L/n64sdk/ultra/usr/lib -L/n64sdk/nintendo/n64kit/nusys/lib -lnusys_d -lgultra_d -L/n64sdk/ultra/GCC/mipse/lib -lkmc
ld: main.o: Relocations in generic ELF (EM: 8)
ld: main.o: Relocations in generic ELF (EM: 8)
ld: main.o: Relocations in generic ELF (EM: 8)
ld: main.o: Relocations in generic ELF (EM: 8)
ld: main.o: Relocations in generic ELF (EM: 8)
ld: main.o: Relocations in generic ELF (EM: 8)
main.o: error adding symbols: File in wrong format
make: *** [Makefile:49: codesegment.o] Error 1
```

For reference, here's the current state of my Makefile:
https://gist.github.com/commandtab/dfcd2448c09604d871053f5723858a75

**Comment by command-tab** [comment]
Compilation success with an updated Makefile!
https://gist.github.com/commandtab/4b816a64e80f7306c7452b2929bf7773

No video output, but that’s a separate issue. Thanks!

**Comment by engerb** [comment]
> Compilation success with an updated Makefile!
> https://gist.github.com/commandtab/4b816a64e80f7306c7452b2929bf7773
> 
> No video output, but that’s a separate issue. Thanks!

Hey @command-tab -- I'm just getting back into this with the the [dockerized modern-dev-kit](https://github.com/Mr-Pnut/portable-n64-toolchain). I'm just trying to build the nusys samples and got to exactly where you seem to get here. The gist link no longer works, do you happen to remember what worked for you?

**Comment by command-tab** [comment]
@engerb Here is a fixed link: https://gist.github.com/command-tab/4b816a64e80f7306c7452b2929bf7773
